[identity_manager://zt_workload_assets]
category = zero_trust
description = Kubernetes workloads, protected AI data stores and their servers
target = asset
url = lookup://zt_es_assets
rank = 1
disabled = 0
