[ztdemo]
filename = ztdemo.py
chunked = true
python.version = python3
python.required = 3.9, 3.13

[ztbrief]
filename = ztbrief.py
chunked = true
python.version = python3
python.required = 3.9, 3.13

[ztsoar]
filename = ztsoar.py
chunked = true
python.version = python3
python.required = 3.9, 3.13
