[script:zt_approvals]
match = /zt_incident_demo/approvals
script = zt_approvals_handler.py
scripttype = persist
handler = zt_approvals_handler.ApprovalsHandler
requireAuthentication = true
passSystemAuth = true
passPayload = true
passHttpHeaders = true
output_modes = json
python.version = python3
python.required = 3.9, 3.13
