[eventtype=zt_flow]
network = enabled
communicate = enabled

[eventtype=zt_process]
process = enabled
report = enabled

[eventtype=zt_ci]
ci = enabled

[eventtype=zt_fabric]
network = enabled
inventory = enabled

[eventtype=zt_enforcement]
change = enabled
